#!/usr/bin/env python3
"""
VIETSUB PRO - 4. SUBTITLE ENGINE
Module: python-engine/media_node/subtitle_engine.py
Components:
- SRT SubRip Generator
- ASS Advanced SubStation Alpha (with styling, karaoke, positioning)
- WebVTT Generator
- CPS (Characters Per Second) Speed Optimization
- Timing Correction (Gap snapping, min duration, overlap fixing)
"""

import math
import logging
from typing import List, Dict, Any, Optional

logging.basicConfig(level=logging.INFO, format="[%(asctime)s] [SubtitleEngine] %(message)s")
logger = logging.getLogger("SubtitleEngine")


class SubtitleEngine:
    DEFAULT_MAX_CPS = 20.0
    DEFAULT_MIN_DURATION = 1.0
    DEFAULT_MAX_GAP_SNAP = 0.25

    @staticmethod
    def format_srt_time(seconds: float) -> str:
        h = int(seconds // 3600)
        m = int((seconds % 3600) // 60)
        s = int(seconds % 60)
        ms = int(round((seconds - int(seconds)) * 1000))
        return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"

    @staticmethod
    def format_ass_time(seconds: float) -> str:
        h = int(seconds // 3600)
        m = int((seconds % 3600) // 60)
        s = int(seconds % 60)
        cs = int(round((seconds - int(seconds)) * 100))
        return f"{h:d}:{m:02d}:{s:02d}.{cs:02d}"

    def optimize_cps(self, cues: List[Dict[str, Any]], max_cps: float = DEFAULT_MAX_CPS) -> List[Dict[str, Any]]:
        """Calculates reading speed in CPS (Characters Per Second) and flags fast segments."""
        result = []
        for cue in cues:
            duration = max(0.1, cue["end"] - cue["start"])
            text = cue.get("translatedText") or cue.get("text") or ""
            cps = round(len(text) / duration, 1)
            warning = cps > max_cps
            c = dict(cue)
            c["cps"] = cps
            c["cpsWarning"] = warning
            result.append(c)
        return result

    def correct_timing(
        self,
        cues: List[Dict[str, Any]],
        min_duration: float = DEFAULT_MIN_DURATION,
        max_gap_snap: float = DEFAULT_MAX_GAP_SNAP
    ) -> List[Dict[str, Any]]:
        """
        Performs broadcast-grade timing normalization:
        1. Ensures minimum duration of 1.0 second per subtitle block.
        2. Snaps tiny pauses/gaps (<250ms) to prevent jarring subtitle flickering.
        3. Resolves overlapping start/end timestamps.
        """
        sorted_cues = sorted(cues, key=lambda c: c["start"])
        corrected = []

        for i, cue in enumerate(sorted_cues):
            c = dict(cue)
            # Min duration check
            if c["end"] - c["start"] < min_duration:
                c["end"] = round(c["start"] + min_duration, 2)

            # Lookahead overlap and gap snap
            if i < len(sorted_cues) - 1:
                next_start = sorted_cues[i + 1]["start"]
                if c["end"] > next_start:
                    c["end"] = next_start
                elif next_start - c["end"] <= max_gap_snap:
                    c["end"] = next_start

            corrected.append(c)
        return corrected

    def export_srt(self, cues: List[Dict[str, Any]]) -> str:
        lines = []
        for i, cue in enumerate(cues, 1):
            lines.append(str(i))
            lines.append(f"{self.format_srt_time(cue['start'])} --> {self.format_srt_time(cue['end'])}")
            lines.append(cue.get("translatedText") or cue.get("text") or "")
            lines.append("")
        return "\n".join(lines)

    def export_ass(self, cues: List[Dict[str, Any]], title: str = "VIETSUB_PRO") -> str:
        header = f"""[Script Info]
; Script generated by VIETSUB PRO Subtitle Engine
Title: {title}
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Plus Jakarta Sans,46,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,2.8,1.5,2,30,30,40,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
        dialogues = []
        for cue in cues:
            start_str = self.format_ass_time(cue["start"])
            end_str = self.format_ass_time(cue["end"])
            speaker = cue.get("speaker", "")
            text = cue.get("translatedText") or cue.get("text") or ""
            dialogues.append(f"Dialogue: 0,{start_str},{end_str},Default,{speaker},0,0,0,,{text}")

        return header + "\n".join(dialogues)

    def export_vtt(self, cues: List[Dict[str, Any]]) -> str:
        lines = ["WEBVTT", ""]
        for i, cue in enumerate(cues, 1):
            s = self.format_srt_time(cue["start"]).replace(",", ".")
            e = self.format_srt_time(cue["end"]).replace(",", ".")
            lines.append(f"{s} --> {e}")
            lines.append(cue.get("translatedText") or cue.get("text") or "")
            lines.append("")
        return "\n".join(lines)


if __name__ == "__main__":
    sub_eng = SubtitleEngine()
    test_cues = [
        {"start": 0.5, "end": 2.0, "translatedText": "Chào mừng đến với VIETSUB PRO."},
        {"start": 2.1, "end": 4.5, "translatedText": "Hệ thống hỗ trợ xuất phụ đề SRT, ASS và VTT chuẩn truyền hình."}
    ]
    print(sub_eng.export_ass(test_cues))
